# Generated by Django 5.0.1 on 2024-02-19 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskgroup_alter_task_due_date_task_taskgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date'], 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.AlterField(
            model_name='task',
            name='taskgroup',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.taskgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('name', 'due_date')},
        ),
    ]
